#!/usr/bin/env bash
#Bash script that will display information about subdomains.

print_funct ()
{
    RECORD_TYPE=$(dig "$SUB_DOMAIN"."$1" | awk '/ANSWER SECTION:/ { getline; print $4 }')
    DESTINATION=$(dig "$2"."$1" | awk '/ANSWER SECTION:/ { getline; print $5 }')
    echo "The subdomain $SUB_DOMAIN is a $RECORD_TYPE record and points to $DESTINATION"
    return 0
}

dig_funct ()
{
    if [ "$2" ]
    then
	SUB_DOMAIN="$2"
	print_funct "$1" "$SUB_DOMAIN"
	return 0
    fi

    SUB_DOMAIN="www"
    print_funct "$1" $SUB_DOMAIN

    SUB_DOMAIN="lb-01"
    print_funct "$1" $SUB_DOMAIN

    SUB_DOMAIN="web-01"
    print_funct "$1" $SUB_DOMAIN

    SUB_DOMAIN="web-02"
    print_funct "$1" $SUB_DOMAIN
}

if [ "$2" ]
then
    dig_funct "$1" "$2"
else
    dig_funct "$1"
fi