#!/usr/bin/env bash
path=$1
ip=$2
user=$3
ssh_key=$4
argss=$#
if [ $argss -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi
	
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path" "$user"@"$ip":~/
