#!/usr/bin/env bash
#customised error page
apt update
apt install nginx -y
echo "Ceci n'est pas une page" >> /var/www/html/404.html
sed -i "/server_name _;/a \\\n\t error_page 404 /404.html \\n\tlocation /404.html{\\n\t root /var/www/html/;\\n\t\internal;\n\t}" /etc/nginx/sites-available/default
service nginx restart

