#!/usr/bin/env bash
#install an haproxy server and configure it 
apt-get update
sudo apt-get install haproxy -y
sudo service haproxy start
sudo sed -i "/504.http/a \\\n\nfrontend myapp\
		\\n\t\tmode http\
		\\n\t\tbind *:80\
		\\n\t\tdefault_backend myapps\
		\\n\n\n\backend myapps\
		\\n\t\t server 17115-web-01  100.25.220.47:80\
		\\n\t\t server 17115-web-02 35.174.208.205:80" /etc/haproxy/haproxy.cfg 
sudo service haproxy restart
