#!/usr/bin/env bash
"It is a protocol that is transferring data in a slow way but surely"
"It is a protocol that is transferring data in a fast way and might loss data along in the process"
"Have you received boxes x, y, z?"
