#!/usr/bin/env bash
#this make the server to post on port :80  in an Ubuntu container.
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
