#!/usr/bin/env bash
#he user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY an#d rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSW#ORD, more info about the user here: USER ID INFO
IFS=:
file="/etc/passwd"
while read -r f1 f2 f3 f4 f5 f6 f7 
do
	echo "The user $f1 is part of the $f4, lives in $f6 and rides $f7.$f3's place is protected by the passcode $f2, more info about the user here:$f5"
done < "$file"
